# Generated by Django 6.0.2 on 2026-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='favorit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
